//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELMAH_Viewer.Configuration
{
    
    
    /// <summary>
    /// The SettingsSection Configuration Section.
    /// </summary>
    public partial class SettingsSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ELMAH_Viewer.Configuration.SettingsSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::ELMAH_Viewer.Configuration.SettingsSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region SavedConnections Property
        /// <summary>
        /// The XML name of the <see cref="SavedConnections"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SavedConnectionsPropertyName = "savedConnections";
        
        /// <summary>
        /// Gets or sets the SavedConnections.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The SavedConnections.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ELMAH_Viewer.Configuration.SettingsSection.SavedConnectionsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=true)]
        public virtual global::ELMAH_Viewer.Configuration.SavedConnectionsCollection SavedConnections
        {
            get
            {
                return ((global::ELMAH_Viewer.Configuration.SavedConnectionsCollection)(base[global::ELMAH_Viewer.Configuration.SettingsSection.SavedConnectionsPropertyName]));
            }
            set
            {
                base[global::ELMAH_Viewer.Configuration.SettingsSection.SavedConnectionsPropertyName] = value;
            }
        }
        #endregion
        
        #region Sources Property
        /// <summary>
        /// The XML name of the <see cref="Sources"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SourcesPropertyName = "sources";
        
        /// <summary>
        /// Gets or sets the Sources.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Sources.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ELMAH_Viewer.Configuration.SettingsSection.SourcesPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ELMAH_Viewer.Configuration.SourcesElement Sources
        {
            get
            {
                return ((global::ELMAH_Viewer.Configuration.SourcesElement)(base[global::ELMAH_Viewer.Configuration.SettingsSection.SourcesPropertyName]));
            }
            set
            {
                base[global::ELMAH_Viewer.Configuration.SettingsSection.SourcesPropertyName] = value;
            }
        }
        #endregion
        
        #region Results Property
        /// <summary>
        /// The XML name of the <see cref="Results"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ResultsPropertyName = "results";
        
        /// <summary>
        /// Gets or sets the Results.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Results.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ELMAH_Viewer.Configuration.SettingsSection.ResultsPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ELMAH_Viewer.Configuration.ResultsElement Results
        {
            get
            {
                return ((global::ELMAH_Viewer.Configuration.ResultsElement)(base[global::ELMAH_Viewer.Configuration.SettingsSection.ResultsPropertyName]));
            }
            set
            {
                base[global::ELMAH_Viewer.Configuration.SettingsSection.ResultsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ELMAH_Viewer.Configuration
{
    
    
    /// <summary>
    /// A collection of ConnectionElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::ELMAH_Viewer.Configuration.ConnectionElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::ELMAH_Viewer.Configuration.SavedConnectionsCollection.ConnectionElementPropertyName)]
    public partial class SavedConnectionsCollection : global::System.Configuration.ConfigurationElementCollection, global::System.Collections.Generic.ICollection<global::ELMAH_Viewer.Configuration.ConnectionElement>
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ConnectionElementPropertyName = "connection";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::ELMAH_Viewer.Configuration.SavedConnectionsCollection.ConnectionElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::ELMAH_Viewer.Configuration.SavedConnectionsCollection.ConnectionElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::ELMAH_Viewer.Configuration.ConnectionElement)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::ELMAH_Viewer.Configuration.ConnectionElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::ELMAH_Viewer.Configuration.ConnectionElement this[int index]
        {
            get
            {
                return ((global::ELMAH_Viewer.Configuration.ConnectionElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::ELMAH_Viewer.Configuration.ConnectionElement this[object name]
        {
            get
            {
                return ((global::ELMAH_Viewer.Configuration.ConnectionElement)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="connection">The <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::ELMAH_Viewer.Configuration.ConnectionElement connection)
        {
            base.BaseAdd(connection);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="connection">The <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::ELMAH_Viewer.Configuration.ConnectionElement connection)
        {
            base.BaseRemove(this.GetElementKey(connection));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::ELMAH_Viewer.Configuration.ConnectionElement GetItemAt(int index)
        {
            return ((global::ELMAH_Viewer.Configuration.ConnectionElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::ELMAH_Viewer.Configuration.ConnectionElement GetItemByKey(string name)
        {
            return ((global::ELMAH_Viewer.Configuration.ConnectionElement)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region ICollection
        /// <summary>
        /// Removes all items from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Clear()
        {
            base.BaseClear();
        }
        
        /// <summary>
        /// Determines whether the <see cref="global::System.Configuration.ConfigurationElementCollection"/> contains a specific value.
        /// </summary>
        /// <param name="connection">The object to locate in the <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/>.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public bool Contains(global::ELMAH_Viewer.Configuration.ConnectionElement connection)
        {
            return (base.BaseIndexOf(connection) >= 0);
        }
        
        /// <summary>
        /// Copies the elements of the <see cref="global::System.Configuration.ConfigurationElementCollection"/> to an <see cref="System.Array"/>, starting at a particular <see cref="System.Array"/> index.
        /// </summary>
        /// <param name="array">The one-dimensional <see cref="System.Array"/> that is the destination of the elements copied from <see cref="global::System.Configuration.ConfigurationElementCollection"/>. The <see cref="System.Array"/> must have zero-based indexing.</param>
        /// <param name="arrayIndex">The zero-based index in <paramref name="array"/> at which copying begins.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void CopyTo(global::ELMAH_Viewer.Configuration.ConnectionElement[] array, int arrayIndex)
        {
            base.CopyTo(array, arrayIndex);
        }
        
        /// <summary>
        /// Gets a value indicating whether the <see cref="global::System.Configuration.ConfigurationElementCollection"/> is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        bool global::System.Collections.Generic.ICollection<global::ELMAH_Viewer.Configuration.ConnectionElement>.IsReadOnly
        {
            get
            {
                return this.IsReadOnly();
            }
        }
        
        /// <summary>
        /// Removes the first occurrence of a specific object from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="item">The <see cref="global::ELMAH_Viewer.Configuration.ConnectionElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        bool global::System.Collections.Generic.ICollection<global::ELMAH_Viewer.Configuration.ConnectionElement>.Remove(global::ELMAH_Viewer.Configuration.ConnectionElement item)
        {
            int idx = base.BaseIndexOf(item);
            if ((idx == -1))
            {
                return false;
            }
            base.BaseRemoveAt(idx);
            return true;
        }
        
        /// <summary>
        /// Returns an enumerator that iterates through the collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public new global::System.Collections.Generic.IEnumerator<global::ELMAH_Viewer.Configuration.ConnectionElement> GetEnumerator()
        {
            global::System.Collections.Generic.List<global::ELMAH_Viewer.Configuration.ConnectionElement> list = new global::System.Collections.Generic.List<global::ELMAH_Viewer.Configuration.ConnectionElement>(base.Count);
            global::System.Collections.IEnumerator iter = base.GetEnumerator();
            for (; iter.MoveNext(); )
            {
                list.Add(((global::ELMAH_Viewer.Configuration.ConnectionElement)(iter.Current)));
            }
            return list.GetEnumerator();
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace ELMAH_Viewer.Configuration
{
    
    
    /// <summary>
    /// The ConnectionElement Configuration Element.
    /// </summary>
    public partial class ConnectionElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ELMAH_Viewer.Configuration.ConnectionElement.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::ELMAH_Viewer.Configuration.ConnectionElement.NamePropertyName]));
            }
            set
            {
                base[global::ELMAH_Viewer.Configuration.ConnectionElement.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region Provider Property
        /// <summary>
        /// The XML name of the <see cref="Provider"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ProviderPropertyName = "provider";
        
        /// <summary>
        /// Gets or sets the Provider.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Provider.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ELMAH_Viewer.Configuration.ConnectionElement.ProviderPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Provider
        {
            get
            {
                return ((string)(base[global::ELMAH_Viewer.Configuration.ConnectionElement.ProviderPropertyName]));
            }
            set
            {
                base[global::ELMAH_Viewer.Configuration.ConnectionElement.ProviderPropertyName] = value;
            }
        }
        #endregion
        
        #region CanDelete Property
        /// <summary>
        /// The XML name of the <see cref="CanDelete"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string CanDeletePropertyName = "canDelete";
        
        /// <summary>
        /// Gets or sets the CanDelete.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The CanDelete.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ELMAH_Viewer.Configuration.ConnectionElement.CanDeletePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool CanDelete
        {
            get
            {
                return ((bool)(base[global::ELMAH_Viewer.Configuration.ConnectionElement.CanDeletePropertyName]));
            }
            set
            {
                base[global::ELMAH_Viewer.Configuration.ConnectionElement.CanDeletePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ELMAH_Viewer.Configuration
{
    
    
    /// <summary>
    /// The SourcesElement Configuration Element.
    /// </summary>
    public partial class SourcesElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Location Property
        /// <summary>
        /// The XML name of the <see cref="Location"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string LocationPropertyName = "location";
        
        /// <summary>
        /// Gets or sets the Location.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Location.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ELMAH_Viewer.Configuration.SourcesElement.LocationPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Location
        {
            get
            {
                return ((string)(base[global::ELMAH_Viewer.Configuration.SourcesElement.LocationPropertyName]));
            }
            set
            {
                base[global::ELMAH_Viewer.Configuration.SourcesElement.LocationPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ELMAH_Viewer.Configuration
{
    
    
    /// <summary>
    /// The ResultsElement Configuration Element.
    /// </summary>
    public partial class ResultsElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region ResultsPerPage Property
        /// <summary>
        /// The XML name of the <see cref="ResultsPerPage"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ResultsPerPagePropertyName = "resultsPerPage";
        
        /// <summary>
        /// Gets or sets the ResultsPerPage.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ResultsPerPage.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ELMAH_Viewer.Configuration.ResultsElement.ResultsPerPagePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual int ResultsPerPage
        {
            get
            {
                return ((int)(base[global::ELMAH_Viewer.Configuration.ResultsElement.ResultsPerPagePropertyName]));
            }
            set
            {
                base[global::ELMAH_Viewer.Configuration.ResultsElement.ResultsPerPagePropertyName] = value;
            }
        }
        #endregion
    }
}
